music/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'songs#index'

  get 'songs', to: 'songs#index'
  get 'songs/new', to: 'songs#new'
  post 'songs/create', to: 'songs#create'
  get 'songs/edit/:id', to: 'songs#edit', as: :songs_edit_path
  patch 'songs/edit/:id', to: 'songs#save_edit'
  delete 'songs/delete/:id', to: 'songs#delete', as: :songs_delete_path
end

music/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music/app/models/song.rb
class Song < ApplicationRecord
  validates :author, presence: true
  validates :name, presence: true
  validates :key, presence: true
  validates :chord, presence: true
  validates :instrument, presence: true
  validates :duration, presence: true

end

music/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    admin == true
  end
end

music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protect_from_forgery with: :exception

  def user_not_authorized
    flash[:danger] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end
end

music/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about]

  def index
    @songs = Song.reorder("created_at DESC").paginate(:page => params[:page], :per_page => 15)
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.create(song_params)
    if @song.save
      flash[:success] = "Addition succeed."
      redirect_to songs_path
    else
      render 'new'
    end


  end

  def edit
    @song = Song.find(params[:id])
    authorize @song, :update?
  end

  def save_edit
    @song = Song.find(params[:id])
    authorize @song, :update?

    @song.update(song_params)

    if @song.save
      flash[:success] = "Song has been edited."
      redirect_to songs_path
    else
      render 'edit'
    end
  end

  def delete
    @song = Song.find(params[:id])

    authorize @song, :update?

    @song.destroy

    flash[:success] = "Song has been deleted."

    redirect_to songs_path
  end

  private

  def song_params
    params.require(:song).permit(:author, :name, :key,
                                    :chord, :instrument, :duration)
  end
end

music/app/helpers/application_helper.rb
module ApplicationHelper
end

music/app/helpers/songs_helper.rb
module SongsHelper
end

music/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Music</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to('Songs', songs_path) %></li>
        <li><%= link_to('Add', songs_new_path) if user_signed_in? %></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
            <li><%= link_to('Login', new_user_session_path)  %> </li>
            <li><%= link_to('Register', new_user_registration_path)  %> </li>
        <% else %>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Songs</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/navigation' %>

  <div class="container">
    <% flash.each do |key, value|  %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>
  </div>

  <footer class="footer">
    <div class="container">
      Copytights Rafal Lewandowski (c)
    </div>
  </footer>
</body>
</html>

music/app/views/songs/_song.html.erb
<tr>
  <td>
    <%= song.author %>
  </td>
  <td>
    <%= song.name %>
  </td>
  <td>
    <%= song.key %>
  </td>
  <td>
    <%= song.chord %>
  </td>
  <td>
    <%= song.instrument %>
  </td>
  <td>
    <%= song.duration %> seconds
  </td>
  <td>
    <%= link_to 'Edit', "/songs/edit/#{song.id}" %> | <%= link_to 'Delete', "/songs/delete/#{song.id}", :method => :delete %>
  </td>
</tr>

music/app/views/songs/edit.html.erb
<h2>Edit song</h2>

<%= form_for(@song, url: "/songs/edit/#{@song.id}") do |f| %>

    <% if @song.errors.any? %>
        <% @song.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    <% end %>

    <div class="form-group">
      <%= f.label :author %><br />
      <%= f.text_field :author, autofocus: true, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :key %><br />
      <%= f.text_field :key, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :chord %><br />
      <%= f.text_field :chord, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :instrument %><br />
      <%= f.text_field :instrument, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :duration %><br />
      <%= f.text_field :duration, class: 'form-control' %>
    </div>

    <%= f.submit "Save", class: 'btn btn-default' %>

<% end %>

music/app/views/songs/index.html.erb
<table class="table table-bordered table-striped">
  <tr>
    <th>Author</th>
    <th>Name</th>
    <th>Key</th>
    <th>Chord</th>
    <th>Instrument</th>
    <th>Duration</th>
    <th></th>
  </tr>

  <%= render @songs %>
</table>

<%= will_paginate @songs, renderer: BootstrapPagination::Rails %>

music/app/views/songs/new.html.erb
<h2>New song</h2>

<%= form_for(@song, url: songs_create_path(@song)) do |f| %>

    <% if @song.errors.any? %>
        <% @song.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    <% end %>

    <div class="form-group">
      <%= f.label :author %><br />
      <%= f.text_field :author, autofocus: true, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :key %><br />
      <%= f.text_field :key, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :chord %><br />
      <%= f.text_field :chord, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :instrument %><br />
      <%= f.text_field :instrument, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :duration %><br />
      <%= f.text_field :duration, class: 'form-control' %>
    </div>


    <%= f.submit "Add", class: 'btn btn-default' %>

<% end %>